version: "3.7"

services:
  streamlit:
    build:
    container_name: my_streamlit_app
    restart: always
    environment:
      DB_HOST: mariadb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8501:8501"
    networks:
      - internal

  mariadb:
    image: mariadb
    container_name: my_mariadb_database
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - my_mariadb:/var/lib/mysql
    networks:
      - internal

caddy:
    image: caddy
    container_name: caddy
    restart: always
    networks:
      - internal
      - public
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  private:
  public:

volumes:
  db-data:


