version: "3.7"

services:
  streamlit:
    image: jimcz/time_streamlit
    container_name: app
    restart: always
    environment:
      DB_HOST: mariadb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - internal
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: my_mariadb_database
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - my_mariadb:/var/lib/mysql
      - ./Schema.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - internal
    depends_on:
      - caddy


  caddy:
    image: caddy
    container_name: caddy
    restart: always
    networks:
      - internal
      - public
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  internal:
  public:

volumes:
  my_mariadb:
